import { DISP } from './constants';

const DISP_FULL_LABEL = {
  '16x2':   'Character LCD 16x2',
  '20x4':   'Character LCD 20x4',
  '128x64': 'Graphic LCD 128x64',
};

function buildRowString(screen, rowIdx, cols) {
  const row = screen.cells[rowIdx] || [];
  let s = '';
  for (let c = 0; c < cols; c++) {
    const inPh = screen.placeholders.find(
      p => p.row === rowIdx && c >= p.col && c < p.col + p.width
    );
    if (inPh) { s += ' '; continue; }

    const ch = row[c] ?? ' ';
    const code = ch.charCodeAt(0);
    if (code >= 0 && code <= 7) {
      // Use HD44780 mirror slot (0x08–0x0F) to avoid embedded NUL
      s += '\\x0' + (code + 8).toString(16);
    } else if (ch === '"') {
      s += '\\"';
    } else if (ch === '\\') {
      s += '\\\\';
    } else if (code < 32 || code > 126) {
      s += '?';
    } else {
      s += ch;
    }
  }
  // Trim trailing spaces — the show helper pads to LCD_COLS automatically
  return s.replace(/ +$/, '');
}

const LIB_LABEL = {
  liquidcrystal_i2c: 'LiquidCrystal_I2C (I2C)',
  liquidcrystal:     'LiquidCrystal (parallel)',
  custom:            'Custom HAL',
};

export function generateHeader(state) {
  const { dt, screens, cgram, targetLib = 'custom', i2cAddr = '0x27' } = state;
  const cfg = DISP[dt] || DISP['16x2'];
  const lines = [];
  const push = (...args) => lines.push(...args);

  const usedCgram = cgram.map((g, i) => (g ? i : -1)).filter(i => i >= 0);
  const lib = targetLib || 'custom';

  // ── File header ──────────────────────────────────────────────────────
  if (lib === 'custom') {
    push(
      '/* =============================================================',
      ' *  Generated by LCD Screen Builder',
      ` *  Display:  ${DISP_FULL_LABEL[dt] || dt}`,
      ` *  Screens:  ${screens.length}`,
      ' * -------------------------------------------------------------',
      ' *  Required user-provided functions (Custom HAL mode):',
      ' *      void lcd_gotoxy(uint8_t col, uint8_t row);',
      ' *      void lcd_putchar(char c);',
      ' *      void lcd_print(const char *s);',
      ' *      void lcd_createChar(uint8_t slot, const uint8_t *data);',
      ' *',
      ' *  --- Quick-start binding for LiquidCrystal:',
      ' *      void lcd_gotoxy(uint8_t c, uint8_t r) { lcd.setCursor(c, r); }',
      ' *      void lcd_putchar(char c)              { lcd.write(c); }',
      ' *      void lcd_print(const char *s)         { lcd.print(s); }',
      ' *      void lcd_createChar(uint8_t s, const uint8_t *d) { lcd.createChar(s, d); }',
      ' *',
      ' *  Dynamic field coordinates are FROZEN.',
      ' * ============================================================= */',
      ''
    );
  } else {
    push(
      '/* =============================================================',
      ' *  Generated by LCD Screen Builder',
      ` *  Display:  ${DISP_FULL_LABEL[dt] || dt}`,
      ` *  Library:  ${LIB_LABEL[lib]}`,
      ` *  Screens:  ${screens.length}`,
      ' * -------------------------------------------------------------',
      ' *  Self-contained — just #include this file and call LCD_Init().',
      ' *  Dynamic field coordinates are FROZEN.',
      ' * ============================================================= */',
      ''
    );
  }

  // ── Include guard + stdlib ────────────────────────────────────────────
  push(
    '#ifndef LCD_SCREENS_H',
    '#define LCD_SCREENS_H',
    '',
    '#include <stdint.h>',
    '',
    '#ifdef __AVR__',
    '  #include <avr/pgmspace.h>',
    '#else',
    '  #define PROGMEM',
    '  #define pgm_read_byte(p) (*(const uint8_t*)(p))',
    '#endif',
    '',
    `#define LCD_COLS ${cfg.cols}`,
    `#define LCD_ROWS ${cfg.rows}`,
    ''
  );

  // ── HAL section ───────────────────────────────────────────────────────
  if (lib === 'liquidcrystal_i2c') {
    const addr = i2cAddr || '0x27';
    push(
      '/* ---- Driver: LiquidCrystal_I2C ----------------------------------------- */',
      '#include <LiquidCrystal_I2C.h>',
      `/* I2C address: ${addr} is the default. Change to 0x3F if your module needs it. */`,
      '#ifndef LCD_I2C_ADDR',
      `  #define LCD_I2C_ADDR ${addr}`,
      '#endif',
      '/* Include this header in only ONE .ino/.cpp file.                             */',
      `static LiquidCrystal_I2C _lcd(LCD_I2C_ADDR, LCD_COLS, LCD_ROWS);`,
      'static inline void LCD_Init(void)                               { _lcd.init(); _lcd.backlight(); }',
      'static inline void lcd_gotoxy(uint8_t c, uint8_t r)            { _lcd.setCursor(c, r); }',
      'static inline void lcd_putchar(char c)                         { _lcd.write(c); }',
      'static inline void lcd_print(const char *s)                    { _lcd.print(s); }',
      'static inline void lcd_createChar(uint8_t s, const uint8_t *d){ _lcd.createChar(s, (uint8_t*)d); }',
      ''
    );
  } else if (lib === 'liquidcrystal') {
    push(
      '/* ---- Driver: LiquidCrystal (parallel 4-bit) -------------------------------- */',
      '#include <LiquidCrystal.h>',
      '/* Override pin defaults before #include if needed:',
      ' *   #define LCD_RS 12   #define LCD_EN 11',
      ' *   #define LCD_D4  5   #define LCD_D5  4   #define LCD_D6  3   #define LCD_D7  2   */',
      '#ifndef LCD_RS',
      '#  define LCD_RS 12',
      '#  define LCD_EN 11',
      '#  define LCD_D4  5',
      '#  define LCD_D5  4',
      '#  define LCD_D6  3',
      '#  define LCD_D7  2',
      '#endif',
      '/* Include this header in only ONE .ino/.cpp file.                             */',
      'static LiquidCrystal _lcd(LCD_RS, LCD_EN, LCD_D4, LCD_D5, LCD_D6, LCD_D7);',
      'static inline void LCD_Init(void)                               { _lcd.begin(LCD_COLS, LCD_ROWS); }',
      'static inline void lcd_gotoxy(uint8_t c, uint8_t r)            { _lcd.setCursor(c, r); }',
      'static inline void lcd_putchar(char c)                         { _lcd.write(c); }',
      'static inline void lcd_print(const char *s)                    { _lcd.print(s); }',
      'static inline void lcd_createChar(uint8_t s, const uint8_t *d){ _lcd.createChar(s, (uint8_t*)d); }',
      ''
    );
  } else {
    push(
      '/* ---- HAL forward declarations — implement these in your sketch ---- */',
      'extern void lcd_gotoxy(uint8_t col, uint8_t row);',
      'extern void lcd_putchar(char c);',
      'extern void lcd_print(const char *s);',
      'extern void lcd_createChar(uint8_t slot, const uint8_t *data);',
      ''
    );
  }

  // ── CGRAM ─────────────────────────────────────────────────────────────
  if (usedCgram.length) {
    push(
      '/* ---- Custom characters (CGRAM)',
      ' *  HD44780 has 8 user-definable 5x8 glyphs at codes 0x00-0x07,',
      ' *  mirrored at 0x08-0x0F. The static line strings below use the',
      ' *  mirror codes (\\x08-\\x0F) to avoid NUL termination.',
      ' *',
      ' *  Call LCD_LoadCGRAM() once after lcd_init(). User must provide:',
      ' *      void lcd_createChar(uint8_t slot, const uint8_t *data);  // 8 bytes',
      ' * ---- */',
      ''
    );
    usedCgram.forEach(i => {
      const g = cgram[i];
      const bytes = g.map(b => '0x' + b.toString(16).padStart(2, '0')).join(', ');
      push(`static const uint8_t cgram_${i}[8] PROGMEM = { ${bytes} };`);
    });
    push('');
    push('static inline void LCD_LoadCGRAM(void) {');
    push('    uint8_t _buf[8];');
    usedCgram.forEach(i => {
      push(`    for (uint8_t i = 0; i < 8; i++) _buf[i] = pgm_read_byte(&cgram_${i}[i]);`);
      push(`    lcd_createChar(${i}, _buf);`);
    });
    // HD44780: createChar() leaves the controller in CGRAM-write mode.
    // Calling lcd_gotoxy() switches it back to DDRAM mode so subsequent
    // write() calls go to the display instead of CGRAM.
    push('    lcd_gotoxy(0, 0);');
    push('}');
    push('');
  }

  // ── Per-screen ────────────────────────────────────────────────────────
  screens.forEach(s => {
    const nameUp    = s.name.replace(/[^a-zA-Z0-9]/g, '_').toUpperCase();
    const namePascal = s.name.replace(/[^a-zA-Z0-9]/g, '_');
    const rows = s.cells.length;
    const cols = s.cells[0]?.length || cfg.cols;
    const sep = '─'.repeat(Math.max(2, 48 - s.name.length));

    push(`/* ---- Screen: ${s.name} ${sep} */`);
    push('');

    // Field coordinate #defines
    if (s.placeholders.length) {
      s.placeholders.forEach(p => {
        const fn = p.name.replace(/[^a-zA-Z0-9]/g, '_').toUpperCase();
        push(`#define ${nameUp}_${fn}_COL   ${p.col}`);
        push(`#define ${nameUp}_${fn}_ROW   ${p.row}`);
        push(`#define ${nameUp}_${fn}_WIDTH ${p.width}`);
      });
      push('');
    }

    // Static row strings
    for (let r = 0; r < rows; r++) {
      const rowStr = buildRowString(s, r, cols);
      push(`static const char ${namePascal}_static_line${r}[] PROGMEM = "${rowStr}";`);
    }

    // Array of row pointers
    push(`static const char * const ${namePascal}_static_lines[${rows}] = {`);
    push(
      Array.from({ length: rows }, (_, r) => `    ${namePascal}_static_line${r}`).join(',\n')
    );
    push('};');
    push('');

    // LCD_Show_*_Static()
    push(`static inline void LCD_Show_${namePascal}_Static(void) {`);
    push(`    for (uint8_t row = 0; row < ${rows}; row++) {`);
    push(`        lcd_gotoxy(0, row);`);
    push(`        const char *p = ${namePascal}_static_lines[row];`);
    push(`        for (uint8_t col = 0; col < ${cols}; col++) {`);
    push(`            char c = (char)pgm_read_byte(p + col);`);
    push(`            if (c == '\\0') { while (col++ < ${cols}) lcd_putchar(' '); break; }`);
    push(`            lcd_putchar(c);`);
    push(`        }`);
    push(`    }`);
    push('}');
    push('');

    // Per-field LCD_Update_*() helpers — overloaded for const char*, int, float
    s.placeholders.forEach(p => {
      const fn   = p.name.replace(/[^a-zA-Z0-9]/g, '_').toUpperCase();
      const fnLo = p.name.replace(/[^a-zA-Z0-9]/g, '_');
      const W    = `${nameUp}_${fn}_WIDTH`;
      push(`/* Update '${p.name}' at col=${p.col}, row=${p.row}, width=${p.width}. Accepts const char*, int, or float. */`);
      // string overload (base)
      push(`static inline void LCD_Update_${namePascal}_${fnLo}(const char *value) {`);
      push(`    lcd_gotoxy(${nameUp}_${fn}_COL, ${nameUp}_${fn}_ROW);`);
      push(`    uint8_t i = 0;`);
      push(`    while (i < ${W} && value[i]) { lcd_putchar(value[i]); i++; }`);
      push(`    while (i < ${W}) { lcd_putchar(' '); i++; }`);
      push('}');
      // int overload
      push(`static inline void LCD_Update_${namePascal}_${fnLo}(int value) {`);
      push(`    char _b[${p.width + 1}]; snprintf(_b, sizeof(_b), "%d", value);`);
      push(`    LCD_Update_${namePascal}_${fnLo}(_b);`);
      push('}');
      // float overload
      push(`static inline void LCD_Update_${namePascal}_${fnLo}(float value, uint8_t decimals = 1) {`);
      push(`    char _b[${p.width + 1}]; dtostrf(value, ${p.width}, decimals, _b);`);
      push(`    LCD_Update_${namePascal}_${fnLo}(_b);`);
      push('}');
      push('');
    });
  });

  // ── Setpoints ─────────────────────────────────────────────────────────
  // Collect editable placeholders across all screens
  const editableFields = [];
  screens.forEach((s, si) => {
    const nameUp     = s.name.replace(/[^a-zA-Z0-9]/g, '_').toUpperCase();
    const namePascal = s.name.replace(/[^a-zA-Z0-9]/g, '_');
    s.placeholders.filter(p => p.editable).forEach((p, localEi) => {
      editableFields.push({ s, si, p, localEi, nameUp, namePascal });
    });
  });

  if (editableFields.length) {
    push('/* ---- Setpoint variables', ' *  Each editable field has a backing int16_t variable and min/max/step bounds.', ' *  Read sp_* in your sketch to get the current value.', ' * ---- */');
    push('');
    editableFields.forEach(({ s, si, p, localEi, nameUp, namePascal }) => {
      const fn    = p.name.replace(/[^a-zA-Z0-9]/g, '_').toUpperCase();
      const fnLo  = p.name.replace(/[^a-zA-Z0-9]/g, '_');
      const vname = `sp_${namePascal}_${fnLo}`;
      push(`static int16_t ${vname} = ${p.spDefault ?? 0};`);
      push(`#define ${nameUp}_${fn}_SP_MIN   ${p.spMin  ?? 0}`);
      push(`#define ${nameUp}_${fn}_SP_MAX   ${p.spMax  ?? 100}`);
      push(`#define ${nameUp}_${fn}_SP_STEP  ${p.spStep ?? 1}`);
      push('');
    });

    push('/* ---- Edit-mode state ---- */');
    push('static uint8_t _edit_screen = 0xFF;');
    push('static uint8_t _edit_field  = 0xFF;');
    push('');
    push('static inline void LCD_EditExit(void) { _edit_screen = _edit_field = 0xFF; }');
    push('');

    // Per-field LCD_EditEnter_*()
    editableFields.forEach(({ s, si, p, localEi, nameUp, namePascal }) => {
      const fn   = p.name.replace(/[^a-zA-Z0-9]/g, '_').toUpperCase();
      const fnLo = p.name.replace(/[^a-zA-Z0-9]/g, '_');
      const vname = `sp_${namePascal}_${fnLo}`;
      push(`static inline void LCD_EditEnter_${namePascal}_${fnLo}(void) {`);
      push(`    _edit_screen = ${si}; _edit_field = ${localEi};`);
      push(`    LCD_Update_${namePascal}_${fnLo}(${vname});`);
      push(`    lcd_gotoxy(${nameUp}_${fn}_COL, ${nameUp}_${fn}_ROW);`);
      push('}');
      push('');
    });

    // _nav_edit_apply(delta): updates the active setpoint variable + display
    push('static inline void _nav_edit_apply(int8_t delta) {');
    editableFields.forEach(({ s, si, p, localEi, nameUp, namePascal }) => {
      const fn   = p.name.replace(/[^a-zA-Z0-9]/g, '_').toUpperCase();
      const fnLo = p.name.replace(/[^a-zA-Z0-9]/g, '_');
      const vname = `sp_${namePascal}_${fnLo}`;
      push(`    if (_edit_screen == ${si} && _edit_field == ${localEi}) {`);
      push(`        ${vname} += (int16_t)delta * ${nameUp}_${fn}_SP_STEP;`);
      push(`        if (${vname} < ${nameUp}_${fn}_SP_MIN) ${vname} = ${nameUp}_${fn}_SP_MIN;`);
      push(`        if (${vname} > ${nameUp}_${fn}_SP_MAX) ${vname} = ${nameUp}_${fn}_SP_MAX;`);
      push(`        LCD_Update_${namePascal}_${fnLo}(${vname});`);
      push(`        lcd_gotoxy(${nameUp}_${fn}_COL, ${nameUp}_${fn}_ROW);`);
      push(`        return;`);
      push(`    }`);
    });
    push('}');
    push('');
  }

  // ── Navigation ────────────────────────────────────────────────────────
  const { inputMethod = 'none', navPins = {}, transitions = [] } = state;
  if (inputMethod !== 'none' && screens.length > 1) {
    push('/* ---- Navigation state machine ------------------------------------------- */');
    push('');

    // Screen index #defines
    screens.forEach((s, i) => {
      const nameUp = s.name.replace(/[^a-zA-Z0-9]/g, '_').toUpperCase();
      push(`#define SCREEN_${nameUp} ${i}`);
    });
    push('');

    // Current screen variable + switch helper
    push('static uint8_t _nav_cur = 0;');
    push('');
    push('static inline void LCD_SwitchTo(uint8_t screen) {');
    push('    _nav_cur = screen;');
    push('    switch (screen) {');
    screens.forEach((s, i) => {
      const namePascal = s.name.replace(/[^a-zA-Z0-9]/g, '_');
      push(`        case ${i}: LCD_Show_${namePascal}_Static(); break;`);
    });
    push('    }');
    push('}');
    push('');

    if (inputMethod === '2btn' || inputMethod === '4btn') {
      // Button pin #defines
      if (inputMethod === '2btn') {
        push(`#define NAV_PIN_NEXT   ${navPins.up   ?? 2}`);
        push(`#define NAV_PIN_SELECT ${navPins.select ?? 4}`);
      } else {
        push(`#define NAV_PIN_UP     ${navPins.up     ?? 2}`);
        push(`#define NAV_PIN_DOWN   ${navPins.down   ?? 3}`);
        push(`#define NAV_PIN_SELECT ${navPins.select ?? 4}`);
        push(`#define NAV_PIN_BACK   ${navPins.back   ?? 5}`);
      }
      push('');

      // Init — set pin modes
      const pins = inputMethod === '2btn'
        ? ['NAV_PIN_NEXT', 'NAV_PIN_SELECT']
        : ['NAV_PIN_UP', 'NAV_PIN_DOWN', 'NAV_PIN_SELECT', 'NAV_PIN_BACK'];
      push('static inline void LCD_Nav_Init(void) {');
      pins.forEach(p => push(`    pinMode(${p}, INPUT_PULLUP);`));
      push('}');
      push('');

      // Transition table (static const array)
      if (transitions.length) {
        const events = inputMethod === '2btn' ? ['next', 'select'] : ['up', 'down', 'select', 'back'];
        push('/* Transition table: { from_screen, event_index, to_screen } */');
        push(`static const uint8_t _nav_table[][3] = {`);
        transitions.forEach(t => {
          const evIdx = events.indexOf(t.event);
          if (evIdx >= 0) push(`    { ${t.from}, ${evIdx}, ${t.to} },`);
        });
        push('};');
        push(`#define _NAV_TABLE_SIZE (sizeof(_nav_table) / sizeof(_nav_table[0]))`);
        push('');
      }

      // Update function — debounced button reading + state machine
      push('static inline void LCD_Nav_Update(void) {');
      push('    static uint32_t _last = 0;');
      push('    if ((uint32_t)(millis() - _last) < 200UL) return;');
      push('');
      if (inputMethod === '2btn') {
        push('    int8_t ev = -1;');
        push('    if (!digitalRead(NAV_PIN_NEXT))   ev = 0;');
        push('    else if (!digitalRead(NAV_PIN_SELECT)) ev = 1;');
      } else {
        push('    int8_t ev = -1;');
        push('    if      (!digitalRead(NAV_PIN_UP))     ev = 0;');
        push('    else if (!digitalRead(NAV_PIN_DOWN))   ev = 1;');
        push('    else if (!digitalRead(NAV_PIN_SELECT)) ev = 2;');
        push('    else if (!digitalRead(NAV_PIN_BACK))   ev = 3;');
      }
      push('    if (ev < 0) return;');
      push('    _last = millis();');
      // Edit mode: up/next=+1, down=-1, select/back=exit
      if (editableFields.length) {
        push('    if (_edit_field != 0xFF) {');
        if (inputMethod === '4btn') {
          push('        if (ev == 0) { _nav_edit_apply(+1); return; }');
          push('        if (ev == 1) { _nav_edit_apply(-1); return; }');
          push('        if (ev == 2 || ev == 3) { LCD_EditExit(); return; }');
        } else {
          push('        if (ev == 0) { _nav_edit_apply(+1); return; }');
          push('        if (ev == 1) { LCD_EditExit(); return; }');
        }
        push('        return;');
        push('    }');
      }
      if (transitions.length) {
        push('    for (uint8_t i = 0; i < _NAV_TABLE_SIZE; i++) {');
        push('        if (_nav_table[i][0] == _nav_cur && _nav_table[i][1] == (uint8_t)ev) {');
        push('            LCD_SwitchTo(_nav_table[i][2]);');
        push('            return;');
        push('        }');
        push('    }');
      }
      push('}');
      push('');

    } else if (inputMethod === 'rotary') {
      push(`#define NAV_PIN_CLK ${navPins.clk ?? 2}`);
      push(`#define NAV_PIN_DT  ${navPins.dt  ?? 3}`);
      push(`#define NAV_PIN_SW  ${navPins.sw  ?? 4}`);
      push('');
      push('static inline void LCD_Nav_Init(void) {');
      push('    pinMode(NAV_PIN_CLK, INPUT_PULLUP);');
      push('    pinMode(NAV_PIN_DT,  INPUT_PULLUP);');
      push('    pinMode(NAV_PIN_SW,  INPUT_PULLUP);');
      push('}');
      push('');

      if (transitions.length) {
        const events = ['cw', 'ccw', 'press'];
        push('static const uint8_t _nav_table[][3] = {');
        transitions.forEach(t => {
          const evIdx = events.indexOf(t.event);
          if (evIdx >= 0) push(`    { ${t.from}, ${evIdx}, ${t.to} },`);
        });
        push('};');
        push('#define _NAV_TABLE_SIZE (sizeof(_nav_table) / sizeof(_nav_table[0]))');
        push('');
      }

      push('static inline void LCD_Nav_Update(void) {');
      push('    static uint8_t  _last_clk = HIGH;');
      push('    static uint32_t _last_sw  = 0;');
      push('    int8_t ev = -1;');
      push('    uint8_t clk = digitalRead(NAV_PIN_CLK);');
      push('    if (clk != _last_clk && clk == LOW) {');
      push('        ev = (digitalRead(NAV_PIN_DT) != clk) ? 0 : 1; /* 0=CW 1=CCW */');
      push('    }');
      push('    _last_clk = clk;');
      push('    if (ev < 0) {');
      push('        if (!digitalRead(NAV_PIN_SW) && (uint32_t)(millis() - _last_sw) > 250UL) {');
      push('            ev = 2; _last_sw = millis();');
      push('        }');
      push('    }');
      push('    if (ev < 0) return;');
      // Edit mode: CW=+1, CCW=-1, press=exit
      if (editableFields.length) {
        push('    if (_edit_field != 0xFF) {');
        push('        if (ev == 0) { _nav_edit_apply(+1); return; }');
        push('        if (ev == 1) { _nav_edit_apply(-1); return; }');
        push('        if (ev == 2) { LCD_EditExit(); return; }');
        push('        return;');
        push('    }');
      }
      if (transitions.length) {
        push('    for (uint8_t i = 0; i < _NAV_TABLE_SIZE; i++) {');
        push('        if (_nav_table[i][0] == _nav_cur && _nav_table[i][1] == (uint8_t)ev) {');
        push('            LCD_SwitchTo(_nav_table[i][2]);');
        push('            return;');
        push('        }');
        push('    }');
      }
      push('}');
      push('');
    }

    push('/* Usage:');
    push(' *   void setup() { LCD_Init(); LCD_Nav_Init(); LCD_SwitchTo(0); }');
    push(' *   void loop()  { LCD_Nav_Update(); }');
    push(' * ---- */');
    push('');
  }

  push('#endif /* LCD_SCREENS_H */');

  return lines;
}

// ── Syntax highlighter (tokenizer — no sequential regex) ──────────────
const KW = new Set(['static', 'const', 'typedef', 'struct', 'void', 'return',
                    'if', 'else', 'for', 'while', 'break', 'inline', 'uint8_t']);
const TY = new Set(['char', 'int', 'uint8_t']);

function esc(str) {
  return str.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
}

export function syntaxHL(line) {
  const trimmed = line.trimStart();
  if (trimmed.startsWith('/*') || trimmed.startsWith('*') || trimmed.startsWith('//')) {
    return `<span class="c-cm">${esc(line)}</span>`;
  }

  let out = '';
  let i = 0;
  while (i < line.length) {
    const ch = line[i];

    if (ch === '#') {
      let j = i + 1;
      while (j < line.length && /\w/.test(line[j])) j++;
      out += `<span class="c-pp">${esc(line.slice(i, j))}</span>`;
      i = j;
      continue;
    }

    if (ch === '"') {
      let j = i + 1;
      while (j < line.length && line[j] !== '"') {
        if (line[j] === '\\') j++;
        j++;
      }
      j++;
      out += `<span class="c-st">${esc(line.slice(i, j))}</span>`;
      i = j;
      continue;
    }

    if (/[a-zA-Z_]/.test(ch)) {
      let j = i;
      while (j < line.length && /\w/.test(line[j])) j++;
      const word = line.slice(i, j);
      if (KW.has(word)) {
        out += `<span class="c-kw">${esc(word)}</span>`;
      } else if (TY.has(word)) {
        out += `<span class="c-ty">${esc(word)}</span>`;
      } else if (word === 'PROGMEM') {
        out += `<span class="c-fn">${esc(word)}</span>`;
      } else {
        out += esc(word);
      }
      i = j;
      continue;
    }

    if (line[i] === '0' && line[i + 1] === 'x') {
      let j = i + 2;
      while (j < line.length && /[0-9a-fA-F]/.test(line[j])) j++;
      out += `<span class="c-nu">${esc(line.slice(i, j))}</span>`;
      i = j;
      continue;
    }

    if (/\d/.test(ch)) {
      let j = i;
      while (j < line.length && /\d/.test(line[j])) j++;
      out += `<span class="c-nu">${esc(line.slice(i, j))}</span>`;
      i = j;
      continue;
    }

    out += esc(ch);
    i++;
  }

  return out;
}
